// Package SubmodelRegistry provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package SubmodelRegistry

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExtensionValueType.
const (
	XsAnyURI             ExtensionValueType = "xs:anyURI"
	XsBase64Binary       ExtensionValueType = "xs:base64Binary"
	XsBoolean            ExtensionValueType = "xs:boolean"
	XsByte               ExtensionValueType = "xs:byte"
	XsDate               ExtensionValueType = "xs:date"
	XsDateTime           ExtensionValueType = "xs:dateTime"
	XsDecimal            ExtensionValueType = "xs:decimal"
	XsDouble             ExtensionValueType = "xs:double"
	XsDuration           ExtensionValueType = "xs:duration"
	XsFloat              ExtensionValueType = "xs:float"
	XsGDay               ExtensionValueType = "xs:gDay"
	XsGMonth             ExtensionValueType = "xs:gMonth"
	XsGMonthDay          ExtensionValueType = "xs:gMonthDay"
	XsGYear              ExtensionValueType = "xs:gYear"
	XsGYearMonth         ExtensionValueType = "xs:gYearMonth"
	XsHexBinary          ExtensionValueType = "xs:hexBinary"
	XsInt                ExtensionValueType = "xs:int"
	XsInteger            ExtensionValueType = "xs:integer"
	XsLong               ExtensionValueType = "xs:long"
	XsNegativeInteger    ExtensionValueType = "xs:negativeInteger"
	XsNonNegativeInteger ExtensionValueType = "xs:nonNegativeInteger"
	XsNonPositiveInteger ExtensionValueType = "xs:nonPositiveInteger"
	XsPositiveInteger    ExtensionValueType = "xs:positiveInteger"
	XsShort              ExtensionValueType = "xs:short"
	XsString             ExtensionValueType = "xs:string"
	XsTime               ExtensionValueType = "xs:time"
	XsUnsignedByte       ExtensionValueType = "xs:unsignedByte"
	XsUnsignedInt        ExtensionValueType = "xs:unsignedInt"
	XsUnsignedLong       ExtensionValueType = "xs:unsignedLong"
	XsUnsignedShort      ExtensionValueType = "xs:unsignedShort"
)

// Defines values for KeyType.
const (
	AnnotatedRelationshipElement KeyType = "AnnotatedRelationshipElement"
	AssetAdministrationShell     KeyType = "AssetAdministrationShell"
	BasicEventElement            KeyType = "BasicEventElement"
	Blob                         KeyType = "Blob"
	Capability                   KeyType = "Capability"
	ConceptDescription           KeyType = "ConceptDescription"
	DataElement                  KeyType = "DataElement"
	Entity                       KeyType = "Entity"
	EventElement                 KeyType = "EventElement"
	File                         KeyType = "File"
	FragmentReference            KeyType = "FragmentReference"
	GlobalReference              KeyType = "GlobalReference"
	Identifiable                 KeyType = "Identifiable"
	MultiLanguageProperty        KeyType = "MultiLanguageProperty"
	Operation                    KeyType = "Operation"
	Property                     KeyType = "Property"
	Range                        KeyType = "Range"
	Referable                    KeyType = "Referable"
	ReferenceElement             KeyType = "ReferenceElement"
	RelationshipElement          KeyType = "RelationshipElement"
	Submodel                     KeyType = "Submodel"
	SubmodelElement              KeyType = "SubmodelElement"
	SubmodelElementCollection    KeyType = "SubmodelElementCollection"
	SubmodelElementList          KeyType = "SubmodelElementList"
)

// Defines values for MessageMessageType.
const (
	Error     MessageMessageType = "Error"
	Exception MessageMessageType = "Exception"
	Info      MessageMessageType = "Info"
	Undefined MessageMessageType = "Undefined"
	Warning   MessageMessageType = "Warning"
)

// Defines values for ProtocolInformationSecurityAttributesType.
const (
	NONE    ProtocolInformationSecurityAttributesType = "NONE"
	RFCTLSA ProtocolInformationSecurityAttributesType = "RFC_TLSA"
	W3CDID  ProtocolInformationSecurityAttributesType = "W3C_DID"
)

// Defines values for ReferenceType.
const (
	ReferenceTypeExternalReference ReferenceType = "ExternalReference"
	ReferenceTypeModelReference    ReferenceType = "ModelReference"
)

// Defines values for ReferenceParentType.
const (
	ReferenceParentTypeExternalReference ReferenceParentType = "ExternalReference"
	ReferenceParentTypeModelReference    ReferenceParentType = "ModelReference"
)

// Defines values for ServiceDescriptionProfiles.
const (
	HttpsadminShellIoaasAPI30AasxFileServerServiceSpecificationSSP001                     ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP001   ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30AssetAdministrationShellRegistryServiceSpecificationSSP002   ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP001 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30AssetAdministrationShellRepositoryServiceSpecificationSSP002 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30AssetAdministrationShellServiceSpecificationSSP001           ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30AssetAdministrationShellServiceSpecificationSSP002           ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30ConceptDescriptionServiceSpecificationSSP001                 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30DiscoveryServiceSpecificationSSP001                          ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30SubmodelRegistryServiceSpecificationSSP001                   ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30SubmodelRegistryServiceSpecificationSSP002                   ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30SubmodelRepositoryServiceSpecificationSSP001                 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30SubmodelRepositoryServiceSpecificationSSP002                 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30SubmodelRepositoryServiceSpecificationSSP003                 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003"
	HttpsadminShellIoaasAPI30SubmodelRepositoryServiceSpecificationSSP004                 ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004"
	HttpsadminShellIoaasAPI30SubmodelServiceSpecificationSSP001                           ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001"
	HttpsadminShellIoaasAPI30SubmodelServiceSpecificationSSP002                           ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002"
	HttpsadminShellIoaasAPI30SubmodelServiceSpecificationSSP003                           ServiceDescriptionProfiles = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003"
)

// AdministrativeInformation defines model for AdministrativeInformation.
type AdministrativeInformation struct {
	Creator                    *Reference                   `json:"creator,omitempty"`
	EmbeddedDataSpecifications *[]EmbeddedDataSpecification `json:"embeddedDataSpecifications,omitempty"`
	Revision                   *string                      `json:"revision,omitempty"`
	TemplateId                 *string                      `json:"templateId,omitempty"`
	Version                    *string                      `json:"version,omitempty"`
}

// DataSpecificationContent defines model for DataSpecificationContent.
type DataSpecificationContent struct {
	ModelType string `json:"modelType"`
}

// EmbeddedDataSpecification defines model for EmbeddedDataSpecification.
type EmbeddedDataSpecification struct {
	DataSpecification        Reference                `json:"dataSpecification"`
	DataSpecificationContent DataSpecificationContent `json:"dataSpecificationContent"`
}

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Interface           string              `json:"interface"`
	ProtocolInformation ProtocolInformation `json:"protocolInformation"`
}

// Extension defines model for Extension.
type Extension struct {
	Name                    string              `json:"name"`
	RefersTo                *[]Reference        `json:"refersTo,omitempty"`
	SemanticId              *Reference          `json:"semanticId,omitempty"`
	SupplementalSemanticIds *[]Reference        `json:"supplementalSemanticIds,omitempty"`
	Value                   *string             `json:"value,omitempty"`
	ValueType               *ExtensionValueType `json:"valueType,omitempty"`
}

// ExtensionValueType defines model for Extension.ValueType.
type ExtensionValueType string

// GetSubmodelDescriptorsResult defines model for GetSubmodelDescriptorsResult.
type GetSubmodelDescriptorsResult struct {
	PagingMetadata *PagedResultPagingMetadata `json:"paging_metadata,omitempty"`
	Result         *[]SubmodelDescriptor      `json:"result,omitempty"`
}

// Key defines model for Key.
type Key struct {
	Type  KeyType `json:"type"`
	Value string  `json:"value"`
}

// KeyType defines model for Key.Type.
type KeyType string

// LangStringNameType defines model for LangStringNameType.
type LangStringNameType struct {
	Language string `json:"language"`
	Text     string `json:"text"`
}

// LangStringTextType defines model for LangStringTextType.
type LangStringTextType struct {
	Language string `json:"language"`
	Text     string `json:"text"`
}

// Message defines model for Message.
type Message struct {
	Code          *string             `json:"code,omitempty"`
	CorrelationId *string             `json:"correlationId,omitempty"`
	MessageType   *MessageMessageType `json:"messageType,omitempty"`
	Text          *string             `json:"text,omitempty"`
	Timestamp     *time.Time          `json:"timestamp,omitempty"`
}

// MessageMessageType defines model for Message.MessageType.
type MessageMessageType string

// PagedResultPagingMetadata defines model for PagedResultPagingMetadata.
type PagedResultPagingMetadata struct {
	Cursor *string `json:"cursor,omitempty"`
}

// ProtocolInformation defines model for ProtocolInformation.
type ProtocolInformation struct {
	EndpointProtocol        *string                                  `json:"endpointProtocol,omitempty"`
	EndpointProtocolVersion *[]string                                `json:"endpointProtocolVersion,omitempty"`
	Href                    string                                   `json:"href"`
	SecurityAttributes      *[]ProtocolInformationSecurityAttributes `json:"securityAttributes,omitempty"`
	Subprotocol             *string                                  `json:"subprotocol,omitempty"`
	SubprotocolBody         *string                                  `json:"subprotocolBody,omitempty"`
	SubprotocolBodyEncoding *string                                  `json:"subprotocolBodyEncoding,omitempty"`
}

// ProtocolInformationSecurityAttributes defines model for ProtocolInformationSecurityAttributes.
type ProtocolInformationSecurityAttributes struct {
	Key   string                                    `json:"key"`
	Type  ProtocolInformationSecurityAttributesType `json:"type"`
	Value string                                    `json:"value"`
}

// ProtocolInformationSecurityAttributesType defines model for ProtocolInformationSecurityAttributes.Type.
type ProtocolInformationSecurityAttributesType string

// Reference defines model for Reference.
type Reference struct {
	Keys               []Key            `json:"keys"`
	ReferredSemanticId *ReferenceParent `json:"referredSemanticId,omitempty"`
	Type               ReferenceType    `json:"type"`
}

// ReferenceType defines model for Reference.Type.
type ReferenceType string

// ReferenceParent defines model for ReferenceParent.
type ReferenceParent struct {
	Keys []Key               `json:"keys"`
	Type ReferenceParentType `json:"type"`
}

// ReferenceParentType defines model for ReferenceParent.Type.
type ReferenceParentType string

// Result defines model for Result.
type Result struct {
	Messages *[]Message `json:"messages,omitempty"`
}

// ServiceDescription The Description object enables servers to present their capabilities to the clients, in particular which profiles they implement. At least one defined profile is required. Additional, proprietary attributes might be included. Nevertheless, the server must not expect that a regular client understands them.
type ServiceDescription struct {
	Profiles *[]ServiceDescriptionProfiles `json:"profiles,omitempty"`
}

// ServiceDescriptionProfiles defines model for ServiceDescription.Profiles.
type ServiceDescriptionProfiles string

// SubmodelDescriptor defines model for SubmodelDescriptor.
type SubmodelDescriptor struct {
	Administration         *AdministrativeInformation `json:"administration,omitempty"`
	Description            *[]LangStringTextType      `json:"description,omitempty"`
	DisplayName            *[]LangStringNameType      `json:"displayName,omitempty"`
	Endpoints              []Endpoint                 `json:"endpoints"`
	Extensions             *[]Extension               `json:"extensions,omitempty"`
	Id                     string                     `json:"id"`
	IdShort                *string                    `json:"idShort,omitempty"`
	SemanticId             *Reference                 `json:"semanticId,omitempty"`
	SupplementalSemanticId *[]Reference               `json:"supplementalSemanticId,omitempty"`
}

// GetAllSubmodelDescriptorsParams defines parameters for GetAllSubmodelDescriptors.
type GetAllSubmodelDescriptorsParams struct {
	// Limit The maximum number of elements in the response array
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor A server-generated identifier retrieved from pagingMetadata that specifies from which position the result listing should continue
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PostSubmodelDescriptorJSONRequestBody defines body for PostSubmodelDescriptor for application/json ContentType.
type PostSubmodelDescriptorJSONRequestBody = SubmodelDescriptor

// PutSubmodelDescriptorByIdJSONRequestBody defines body for PutSubmodelDescriptorById for application/json ContentType.
type PutSubmodelDescriptorByIdJSONRequestBody = SubmodelDescriptor

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns the self-describing information of a network resource (ServiceDescription)
	// (GET /description)
	GetDescription(c *fiber.Ctx) error
	// Deletes all Submodel Descriptors
	// (DELETE /submodel-descriptors)
	DeleteAllSubmodelDescriptors(c *fiber.Ctx) error
	// Returns all Submodel Descriptors
	// (GET /submodel-descriptors)
	GetAllSubmodelDescriptors(c *fiber.Ctx, params GetAllSubmodelDescriptorsParams) error
	// Creates a new Submodel Descriptor, i.e. registers a submodel
	// (POST /submodel-descriptors)
	PostSubmodelDescriptor(c *fiber.Ctx) error
	// Deletes a Submodel Descriptor, i.e. de-registers a submodel
	// (DELETE /submodel-descriptors/{submodelIdentifier})
	DeleteSubmodelDescriptorById(c *fiber.Ctx, submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}) error
	// Returns a specific Submodel Descriptor
	// (GET /submodel-descriptors/{submodelIdentifier})
	GetSubmodelDescriptorById(c *fiber.Ctx, submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}) error
	// Updates an existing Submodel Descriptor
	// (PUT /submodel-descriptors/{submodelIdentifier})
	PutSubmodelDescriptorById(c *fiber.Ctx, submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetDescription operation middleware
func (siw *ServerInterfaceWrapper) GetDescription(c *fiber.Ctx) error {

	return siw.Handler.GetDescription(c)
}

// DeleteAllSubmodelDescriptors operation middleware
func (siw *ServerInterfaceWrapper) DeleteAllSubmodelDescriptors(c *fiber.Ctx) error {

	return siw.Handler.DeleteAllSubmodelDescriptors(c)
}

// GetAllSubmodelDescriptors operation middleware
func (siw *ServerInterfaceWrapper) GetAllSubmodelDescriptors(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllSubmodelDescriptorsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	return siw.Handler.GetAllSubmodelDescriptors(c, params)
}

// PostSubmodelDescriptor operation middleware
func (siw *ServerInterfaceWrapper) PostSubmodelDescriptor(c *fiber.Ctx) error {

	return siw.Handler.PostSubmodelDescriptor(c)
}

// DeleteSubmodelDescriptorById operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubmodelDescriptorById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "submodelIdentifier" -------------
	var submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}

	err = runtime.BindStyledParameterWithOptions("simple", "submodelIdentifier", c.Params("submodelIdentifier"), &submodelIdentifier, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter submodelIdentifier: %w", err).Error())
	}

	return siw.Handler.DeleteSubmodelDescriptorById(c, submodelIdentifier)
}

// GetSubmodelDescriptorById operation middleware
func (siw *ServerInterfaceWrapper) GetSubmodelDescriptorById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "submodelIdentifier" -------------
	var submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}

	err = runtime.BindStyledParameterWithOptions("simple", "submodelIdentifier", c.Params("submodelIdentifier"), &submodelIdentifier, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter submodelIdentifier: %w", err).Error())
	}

	return siw.Handler.GetSubmodelDescriptorById(c, submodelIdentifier)
}

// PutSubmodelDescriptorById operation middleware
func (siw *ServerInterfaceWrapper) PutSubmodelDescriptorById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "submodelIdentifier" -------------
	var submodelIdentifier struct {
		Char     *string  `json:"char,omitempty"`
		Direct   *bool    `json:"direct,omitempty"`
		Double   *float64 `json:"double,omitempty"`
		Float    *float32 `json:"float,omitempty"`
		Int      *int32   `json:"int,omitempty"`
		Long     *int64   `json:"long,omitempty"`
		ReadOnly *bool    `json:"readOnly,omitempty"`
		Short    *int32   `json:"short,omitempty"`
	}

	err = runtime.BindStyledParameterWithOptions("simple", "submodelIdentifier", c.Params("submodelIdentifier"), &submodelIdentifier, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter submodelIdentifier: %w", err).Error())
	}

	return siw.Handler.PutSubmodelDescriptorById(c, submodelIdentifier)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/description", wrapper.GetDescription)

	router.Delete(options.BaseURL+"/submodel-descriptors", wrapper.DeleteAllSubmodelDescriptors)

	router.Get(options.BaseURL+"/submodel-descriptors", wrapper.GetAllSubmodelDescriptors)

	router.Post(options.BaseURL+"/submodel-descriptors", wrapper.PostSubmodelDescriptor)

	router.Delete(options.BaseURL+"/submodel-descriptors/:submodelIdentifier", wrapper.DeleteSubmodelDescriptorById)

	router.Get(options.BaseURL+"/submodel-descriptors/:submodelIdentifier", wrapper.GetSubmodelDescriptorById)

	router.Put(options.BaseURL+"/submodel-descriptors/:submodelIdentifier", wrapper.PutSubmodelDescriptorById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w723LjNrK/guLJg5VDSrKtzEUvObJlTVRnxuOyPMkmlnYKIlskxiDAAUBbiqWq/Y39",
	"vf2SLYCELiQty97xTJL1iwzi0uhudDe6G+1bx+dxwhkwJZ32rSP9CGJsmp0gJoxIJbAi19BnEy5irAhn",
	"ejARPAGhCJipvgCsuNDN7wRMnLbzP40V3EYOtHEOExDAfHAWrgPxGIIAgi5WeJCATybEN+ANRKIglvfB",
	"O7kLhIYf42k/A3Kw33rZenX4ovXSdWLC8t5911GzBJy2g4XAM71EwDWRlkCsFAjmtJ2/7zXnl/ve69Fl",
	"03s9um26h4vad85ytVSCsFAvVxAnFCvoBxpAjKdvgYUqctoHzWbTbG079t0N+JfDoRoO2XAo0HCYBi8n",
	"k+EwhWaz6Q2H6WQyCUZz3f+q2bzUf/1sIJhMJqP5ZTayb3rGExiVp2Qjk9JA7ftKMq5BPJoJi2UPH38C",
	"X2l4pdM55kwBU3qDgEhfkJgwKz65XM1OcayhxDwAeqEhLtyCzK2G2rcVaAj4nBIBgdO+XJs6qsDvbikq",
	"yXlQNWVniQ+2MGIbkDsZWKSzjN6WTStZwYKEkwyjTcoJUyAm2IeCaO8fvKoQoURwxX1OC0ZjG5FnFUuK",
	"9K2QqN6ikqSpAiYrT5MZGSuTs5Oien8ATRVauuQF39lgbojjIwykhBgzRfzMwu28k0yThEIMTGE6WIKQ",
	"Xw3ta0zTKjORj1gjAiyNtZhNZRuz2YfzvuPq9hhLeNE6IgyLWd7DOQXM8o+ZgqwV4PXWBYntF/gkxjT/",
	"4OmY2oFUWDWdyvaEcqyyZtjF+VbhO85UtN5eDf0KWKw112ZGMF3HV2u0bUAI+SLKWZi1GIT5Hb82zDg7",
	"vaP/jEtS6k+qOmXERb53znTTVkvepEySkEFwtOSi7elbpG3H2yW+tmdgoI/ce8y/0fMq2/AG1CAdm9uh",
	"C/oiShQX8hxkSitMYIJDwsKPMSisjeq9Bg2HEGSwzszKd3ahQc/usZMClLF0FkUxr7p6/x9mZTpUQdw7",
	"jHGFlUaWZg5YRJKTTF8d1+lICWrdF+RsEAHV4nyEJfFProGp1fQjyseO6xzjBI8JJUqL4DFnPiTKYp9J",
	"vL7VVstOmMrmFsD1iFGWnsCh7llZAtd5Q/kY0/WefgBMkQnBmYa9S6kibzELUxzCWe5YOK7zPoGl3q11",
	"n2MW6mUGYg5iCX2FUTWX7AmtNcuDec8xpxT8HIHC2FsiqyR6zYY9zq/89tdVQSnNqCWrSjn1wQ3MWu0L",
	"Whu9Kco0P9yir7p3ib3fO95vo9sD93Cx5y0/Cx+124NF7cf5sqe1WLV/cF8tamuzW4vaj3veGuTFPPOF",
	"Dxc1M2KHdGfNLM8mbPbr2d/veXqk4/3yq/cb9m5m3u+jFehs3oHe/n/N1OnfSqP72eiP87sH53t7wLw3",
	"Rx6HYE48HJM58caMzYkXwASnVM2JB4z7EcG6M8JXc+JdUcJCrr9pOp0TL9afc+IxfI0/6UZyowcV5uZ3",
	"pn9lOpch845OvN65bZ2+Na3jn7zuSW2+h4XyKP80xmzuA/VCnFIioznj3phf6T9sxua/R16Y8lmqGxG+",
	"usK6EROW//EYNs0pwSys1e6KwabqT+zTFZRkKd85Ydv15AKm6llPnvXksXrSPDj8KyvKO5DS6sBm9ooH",
	"xZv18KDIiRIHfS5E7gqUEj4VJqe0Ps7QKQYfH1gAE8Ig0P4Mm3DHdX7BgmWu84kQXHvWJ1PtT22GvOWz",
	"LQ+QGKTCcaJHs7DZaTs6WPFyj3yHdM7dfm2ZsamQWVpnF7jVOYNNiJAnKOzknbIRxUU/rxJcS++7zKtC",
	"DBkZ97zgfrWqtpPgp4KoWUcpQcapgt0D3QoeDMrQHhm7p+PkIVxbm3/Eg9lj1pwwnwd66P61BX023B7t",
	"JiWDSn5vys1VFgjdccor7Tt9f3qiffze8ceLt4OOVr7D44/dfne7T76dGL25e7/Du4pkqtDfXYh00PfY",
	"/PcEhIBg8PA0zxkWJiNZZunJVN8gm4HaOx3xrDrujeAN/fmkrazL0fhWDPw2tFenK/L7ZXey7f24U2Zh",
	"AOKa+LAe0rdvnWD907mIAK1NQNlqBEwH1xJJENcgJFIcJQIkMIVUBEQg3+YOCJhRFQHyKdHIuogwlGCh",
	"iJ9SLNBNRPwIJYJPiAapIpghEufJxjrqKEQBS4U4A5Tfq3Y2IhJZPtdRJwiIRhJTV09IBAGFxQzhpVFB",
	"MQkjhcaACPNpGuhVp3ANQkVAQUrX4JkRheJUKsS4QjBNNM0qwgphJCA0aGfUoJQFIKTCLDCox3Wn+Mhh",
	"Kds4RCtdkVKJbDcaONBen4yA0jrhDYxlo3PWbxw2mo27kjf58W08DDQGgzOv2dx33CeCfLAbZJsR+c9x",
	"3AHSl8PpcEe+YTntEQoDIyhPdw7nEOqO2Tfd4YHc/XI4PwDijjh2ifT5NTwtQ00OnX/zPR58bF8O7wfB",
	"fAo8D58AZms3mOU0+VZ+jtyNYGTTR9kaeT7Usal0AMpPEiUXBG/I333+x931Jgt307PY0aGpyIxVBHYB",
	"kQnFecHBgyEvc9MVkG3c+YCCFvv+/jj3E+xb9wN2XD6PP25L8sBal8vhcNp8rX86+qc7HE4PTKqn+7LX",
	"Gw7Tkzyd1Ov1usNhut/Mv/ebvV6vN6p+Byf5S+BOIeqXfML+Si/YhYhgJVeG/+WgQC8gbMKz5BZT2De8",
	"gRgT6rTN0P+RQN0QVucidNy8EsLpsyDVnMIUdUlIFKbo4oYw1JGS+8ToItrrdy86tZJKGme/l1KKznL3",
	"mk+MQ2ztBLJXMcqNGtqwaghL49fbZZebo3mvudXQ5rWGzL3WRmd69cFoTxvadqNBlrQEGSmW3Aawhp/V",
	"wHhROq7VEUJn6ZgSGYFoo915gDqJIBQdNA/0nUGJD0zCqq7EOT5GR7+iVr3puE4qNOPtHWDK5cg1+DyO",
	"OZMGq3y9bIxnjVa92cjydYpqSF2uOp1BTiGao58uLs4a5yeDCzTflb/OWl2X8/NhvVnf/2gvkoXr8AQY",
	"TojTdsyQY3Q2MmLdKJjeEIwwcfuIqrXAeQOF110BMuGaHj33oNm0ophH5zhJqL3PPskMcKYr9z6FlwNP",
	"I++b0ngOn1OQCgK0MdF1Ws3DL4ZKHnlXbN/jYkyCAPKry7wifIVtu9lOCITgAkWYBZSwEE24QCnTtotw",
	"HQBLhVUqkc8DkMa4yDSOsZgZvqlUMJmHsnTiZRuMNRiyupG1PmLEQN1wcYUESJ4KH9Be+XBq2l7jUGq7",
	"VRJVZ6R3b8i83wtWRRhZNoGCgrKwdU1/h9KK4o2y6LXKiYlTjvy1EroV+RlkiTClK8XahL6NGPdO5bgT",
	"2QQLHIMCTfFlVQIlxlMSpzFiaTwGoRkP2T0kEWHmnCy9KLsttOl32s7nFEz5T26MKImJctw1EVvm/wlT",
	"h9qT1kY1TuP1+8fWCy0WbhG3Tp7q8EJgmlgIEMnLL0AgAUoQuIYATQSPUbLxUJBlQ2RmnkBmU/JMjiki",
	"4kvCtDRTIpWWPxnxlAbm5AhL4Q5C8zeHdUqL+bXRE5qnrSVFWw1VpbwZi9X8CqbjCAcox8VFUA/r+QmY",
	"HrSSUnsTZ9Jjv+y8MQ9miEh0IzgL69/I3rYylX/iLU+5Qj2eskBv+cNXOaM+y7LJKMsdoew18E96wzza",
	"xCZcVtjYMy4rFM/JHGeQyj5hfRkfpKIcb9NJVyKFRcnM7D85BpunVcFfZHxPfUSp74OUk5TS2bOZeZSZ",
	"ef0VtjzmbEKJr1zzepD7WdldKSOtQ2NYHilMiVRaswTgYFZH7+yDhYoEv2GIaKdtKRNcoELtIbohKspc",
	"PxwDMjF1P9CMNkGkeTwhDGF09n5wYQ+j/mczQMeGW9L4rzdVJshFpA51JIzR0bKIkVxVdz7GmW3c2t7+",
	"0kVa3O/hlpX8aNYPdnEa7cp//eOfEqWMfE4BkQDtfbjovfKOOoOTFy3vw/lbD5jmUFCzvpQO+lauVBlp",
	"p2jj1t2sQu1HhEXlk3tABPjr9Sm2ml6PZcXxG9Uptl4+n535wXpyVi+/PtdW0Jem5v/SUnJ5i26u65ii",
	"+MLUF63KqVrL3jM6qyZF2ozUvZuWs6sVHmpFFFNl3TOBerbuz07kA53I6jB4i3kMwHuEhbw7Qn42ds/G",
	"7gmyhTv5yVuD8Gfz+Ww+/6oxuE3C+ZWCf28knlYF4umzKf/vNuV/nHzLjk5zmgTPKZFnq/9Xt/ofjJhL",
	"hFmWKdLLH272DcyscrfCiL9ZPgblhbCpoBvP3+1Gg3If04hL1X7VfHXoaKORb1iEVl0/0Dnrr2x9GcXF",
	"aPHvAAAA//8tRuDW1UYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
