# yaml-language-server: $schema=../../../../configuration-schema.json
package: api
generate:
  fiber-server: true
  embedded-spec: true
  models: true
output: conceptDescription/concept_description.gen.go